# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Ensure schema is created before data.sql runs
spring.jpa.defer-datasource-initialization=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server port
server.port=8085
